### ISSUE TITLE
Prevent from cheating with switching to Spymaster

### ISSUE THREAD

**Issue by tart2000** [jbowens/codenames#97] opened 2020-04-27 08:50 UTC
Here are two ideas to prevent people from cheating: 

- Block switching to Spymaster after the game has started. You could have a screen before seeing the game that asks you which role you want to take and it blocks it for the rest of the game. 
- Make it visible to other players when someone switches to Spymaster (for example, a thing that counts the number of active Spymaster screens and flashes if it changes during the game). 

Thanks again for this app. We've had some really fun time playing. 
Keep up the good work.

**Comment by jbowens** [comment] 2020-05-03 18:10
Duplicate of #66

**Closed as completed by jbowens** 2020-05-03 18:10 UTC
